# permissions for end users to edit cells.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cell-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: monitoring-cell
    app.kubernetes.io/part-of: monitoring-cell
    app.kubernetes.io/managed-by: kustomize
  name: cell-editor-role
rules:
- apiGroups:
  - monitoring.gitpod.io
  resources:
  - cells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.gitpod.io
  resources:
  - cells/status
  verbs:
  - get
